Repository Mnseo/Kusitms_android, pull requests merged in 2023-12, with the labels that each got.

#42 Mod: SettingUI & Add: SettingViewModel
  data/build.gradle
  data/src/androidTest/java/com/kusitms/data/ExampleInstrumentedTest.kt
  data/src/main/java/com/kusitms/data/response/SignInDataSource.kt
  data/src/test/java/com/kusitms/data/ExampleUnitTest.kt
  domain/src/main/java/com/kusitms/data/MyClass.kt
  domain/src/main/java/com/kusitms/data/entity/member/Member.kt
  domain/src/main/java/com/kusitms/data/model/SignInCondition.kt
  domain/src/main/java/com/kusitms/data/model/SignInExtraCondition.kt
  domain/src/main/java/com/kusitms/data/model/linkCategory.kt
  domain/src/main/java/com/kusitms/data/repository/LoginRepository.kt
  domain/src/main/java/com/kusitms/data/usecase/LoginUseCase.kt
  domain/src/main/java/com/kusitms/data/usecase/SignInUseCase.kt
  domain/src/main/java/com/kusitms/domain/MyClass.kt
  domain/src/main/java/com/kusitms/domain/repository/LoginRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/LoginUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/SignInUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsScaffoldNonScroll.kt
  presentation/src/main/java/com/kusitms/presentation/model/setting/SettingUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/HomeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCheckEmail.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCodeValidation.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwMemberCurrent.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwSetNewPw.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/manager/LoginManagerScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/nonMember/NonMemberScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingMember.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingNonMember.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingToggle.kt
  presentation/src/main/res/values/strings.xml
Labels: fix, design

#47 Mod profile setting bottom sheet
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInDefaultProfile.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/LikeCategoryBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/PartBottomSheet.kt
Labels: feature

#46 Add 공지사항 더보기, 신고
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsDialog.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
Labels: feature

#49 Error: Gradle(:app)
  build.gradle
  data/build.gradle
  data/src/main/java/com/kusitms/data/LoginRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/remote/di/NetworkModule.kt
  data/src/main/java/com/kusitms/data/remote/entity/ApiResult.kt
  data/src/main/java/com/kusitms/data/remote/entity/BaseResponse.kt
  domain/build.gradle
  domain/src/main/java/com/kusitms/domain/entity/response/LoginResponse.kt
  domain/src/main/java/com/kusitms/domain/repository/LoginRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/LoginUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/behance.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberScreen.kt
  presentation/src/main/res/drawable/ic_link.xml
  presentation/src/main/res/drawable/ic_tistory.png
Labels: help wanted

#50 Add image icon
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsTopBar.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitsmButton.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/__KusitmsIcons.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/ArrowDown.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Chat.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Checked.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Close.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Download.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Flag.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/MoreVertical.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Notice.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/NoticeDark.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Search.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Send.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Setting.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/Unchecked.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/User.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/UserBackground.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/CurriculumListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
  presentation/src/main/res/drawable/logo_background.png
Labels: feature

#51 Refactor: Api처리 Domain->data
  app/src/debug/ic_launcher-playstore.png
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/debug/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/debug/res/mipmap-hdpi/ic_launcher.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-hdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-mdpi/ic_launcher.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-mdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/debug/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/debug/res/values/ic_launcher_background.xml
  app/src/main/java/com/kusitms/kusitms/KusitmsApp.kt
  app/src/main/res/drawable/app_icon.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  data/build.gradle
  data/src/main/java/com/kusitms/data/LoginRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/local/AuthDataStore.kt
  data/src/main/java/com/kusitms/data/local/DataStoreUtils.kt
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/di/AuthTokenInterceptor.kt
  data/src/main/java/com/kusitms/data/remote/di/NetworkModule.kt
  data/src/main/java/com/kusitms/data/remote/entity/ApiResult.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/LoginMemberProfileResponse.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/LoginResponse.kt
  domain/build.gradle
  domain/src/main/java/com/kusitms/domain/MyClass.kt
  domain/src/main/java/com/kusitms/domain/model/SignInProfile.kt
  domain/src/main/java/com/kusitms/domain/model/login/LoginMemberProfile.kt
  domain/src/main/java/com/kusitms/domain/repository/LoginRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/LoginUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/LoginViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberInputColumn.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberScreen.kt
Labels: feature, fix

#54 Add comment and report usecase
  domain/src/main/java/com/kusitms/domain/model/notice/CommentContentModel.kt
  domain/src/main/java/com/kusitms/domain/model/notice/CommentModel.kt
  domain/src/main/java/com/kusitms/domain/model/report/ReportContentModel.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/AddNoticeCommentUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/DeleteCommentUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/GetNoticeCommentListUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/report/ReportUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/model/notice/CommentUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
Labels: feature

#59 [FEAT] 댓글 삭제, 커리큘럼 공지사항 연동 및 etc
  data/src/main/java/com/kusitms/data/NoticeRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/notice/NoticePayload.kt
  domain/src/main/java/com/kusitms/domain/model/notice/NoticeModel.kt
  domain/src/main/java/com/kusitms/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/DeleteCommentUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/GetCurriculumListUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/GetCurriculumNoticeListUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/GetNoticeCommentListUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/GetNoticeDetailUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/GetNoticeListUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/CurriculumListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
Labels: ✨ feature

#60 [FEAT] 회원 가입 및 로그인 이전 비밀번호 찾기 연동
  data/src/main/java/com/kusitms/data/LoginRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/local/AuthDataStore.kt
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/di/AuthTokenInterceptor.kt
  data/src/main/java/com/kusitms/data/remote/di/NetworkModule.kt
  data/src/main/java/com/kusitms/data/remote/di/RepositoryModule.kt
  data/src/main/java/com/kusitms/data/remote/entity/request/UpdatePasswordRequest.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/FindPwCheckEmailResponse.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/SignInRequestResponse.kt
  data/src/main/java/com/kusitms/data/repository/FindPwRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/SignInRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/SignInCondition.kt
  domain/src/main/java/com/kusitms/domain/model/SignInExtraCondition.kt
  domain/src/main/java/com/kusitms/domain/model/findpw/FindPwCheckEmailModel.kt
  domain/src/main/java/com/kusitms/domain/model/login/LoginMemberProfile.kt
  domain/src/main/java/com/kusitms/domain/model/signin/SignInProfile.kt
  domain/src/main/java/com/kusitms/domain/model/signin/SignInRequestCheckModel.kt
  domain/src/main/java/com/kusitms/domain/repository/FindPwRepository.kt
  domain/src/main/java/com/kusitms/domain/repository/LoginRepository.kt
  domain/src/main/java/com/kusitms/domain/repository/SignInRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/SignInUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/findpw/FindPwEmailVerifyUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/findpw/FindPwSendCodeUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/GetLoginMemberProfileUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/LoginMemberUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/SignInRequestCheckUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/SignInRequestUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/LoginViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/findPw/FindPwViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInRequestViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCheckEmail.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwMemberCurrent.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPwSetPwInput.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInDefaultProfile.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInRequestScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature

#62 [Feat] : 프로필 메인 화면 UI 제작
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  data/build.gradle
  presentation/build.gradle
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitsmButton.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/PartList.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/ProfileUiState.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/ProfileViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/CurriculumListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/search/ProfileSearchScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 아린

#64 [Feat] : 댓글 신고
  data/src/main/java/com/kusitms/data/NoticeRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/entity/request/ReportCommentRequestBody.kt
  domain/src/main/java/com/kusitms/domain/model/notice/ReportCommentContentModel.kt
  domain/src/main/java/com/kusitms/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/report/ReportUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 석준

#66 [FEAT] 비밀번호 확인 및 변경
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/di/RepositoryModule.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/CheckPasswordPayload.kt
  data/src/main/java/com/kusitms/data/repository/ChangePwRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/repository/ChangePwRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/changepw/CheckPasswordUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/changepw/UpdatePasswordAsLoggedInUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsInputField.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/findPw/FindPwViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/findPw/UpdatePwViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCheckEmail.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCodeValidation.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwMemberCurrent.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwSetNewPw.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPwSetPwInput.kt
Labels: ✨ feature, 석준

#67 [FEAT] 이미지 뷰어 및 스낵바 추가
  data/src/main/java/com/kusitms/data/NoticeRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  domain/src/main/java/com/kusitms/domain/model/report/ReportResult.kt
  domain/src/main/java/com/kusitms/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/report/ReportUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsDialog.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/viewer/ImageViewerScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/viewer/ImageViewerViewModel.kt
  presentation/src/main/res/drawable/rectangle_grey_500.png
Labels: ✨ feature, 석준

#68 [FEAT] 비회원 비밀번호 변경 & 프로필 추가 등록 API 연결
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/di/RepositoryModule.kt
  data/src/main/java/com/kusitms/data/remote/entity/request/UpdatePasswordRequest.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/notice/FindPwCodeVerifyResponse.kt
  data/src/main/java/com/kusitms/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/ChangePwRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/FindPwRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/SignInRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/findpw/FindPwCodeVerifyModel.kt
  domain/src/main/java/com/kusitms/domain/model/findpw/FindPwNewPasswordModel.kt
  domain/src/main/java/com/kusitms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/kusitms/domain/repository/FindPwRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/findpw/FindPwCodeVerifyUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/findpw/FindPwUpdatePasswordUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/AuthMemberProfileUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsSnackField.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/findPw/FindPwViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/findPw/UpdatePwViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SnackbarState.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCheckEmail.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCodeValidation.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwSetNewPw.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInDefaultProfile.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/LikeCategoryBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/PartBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/SignInFixedInput.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature

#69 [FEAT] : 프로필 상세 조회 UI 구현
  .idea/misc.xml
  presentation/src/main/java/com/kusitms/presentation/model/profile/Profile.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailImage.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailInfo.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailScreen.kt
  presentation/src/main/res/drawable/ic_notion.png
  presentation/src/main/res/drawable/ic_profile_logo.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 아린
