Repository Mnseo/Kusitms_android, pull requests merged in 2023-11, with the labels that each got.

#27 [큐시즘 둘러보기] 비회원 플로우 스크린 페이지 이동 확인 및 compose 완료
  .idea/deploymentTargetDropDown.xml
  presentation/src/main/java/com/kusitms/presentation/model/login/nonmember/Channel.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/nonmember/Channels.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/nonMember/NonMemberBanner.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/nonMember/NonMemberPage.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/nonMember/NonMemberScreen.kt
Labels: feature, design

#28 Remove: 공백 제거 & Branch Closed
  presentation/src/main/java/com/kusitms/presentation/ui/login/nonMember/NonMemberScreen.kt
Labels: Branch Close

#30 Fix: 네비게이션 NavHost & Function 수정
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsInputField.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/findPw/FindPwViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/FindPwRoute.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/KusitmsNavigationDestination.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwPwInput.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwScreen1.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwScreen2.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwValidation.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberNavigation.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInScreen3.kt
  presentation/src/main/res/drawable/ic_finpw_warning.xml
  presentation/src/main/res/drawable/ic_warning_sigb.png
  presentation/src/main/res/values/strings.xml
Labels: fix

#31 Add: FindPw - 이메일 Validation 확인된 InputField 컴포넌트 생성 및 Navigation Graph 추가
  presentation/src/main/java/com/kusitms/presentation/model/login/findPw/FindPwViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/FindPwRoute.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/KusitmsNavigationDestination.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/KusitmsScreens.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwScreen1.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwScreen2.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPwBtn1.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPwEmailComVal.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPwPwInput.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPwValidation.kt
  presentation/src/main/res/values/strings.xml
Labels: feature, design

#33 Refactor: 스크린 구조 통일 및 변경
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsScaffoldNonScroll.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/HomeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInAdditionalProfile.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInDefaultProfile.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/PartBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/PartCategoryItem.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/SignInBirthInput.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/SignInFixedInput.kt
Labels: fix, design

#34 Add 공지사항 화면 추가 - 공지사항 탭 화면 UI
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsMarginSpacer.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsTab.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsTopBar.kt
  presentation/src/main/java/com/kusitms/presentation/model/notice/NoticeUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeList.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInProfileComplete.kt
Labels: feature

#37 Add: 회원가입 스크린
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsInputField.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsScaffoldNonScroll.kt
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsSnackField.kt
  presentation/src/main/java/com/kusitms/presentation/model/setting/NonMemberUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInRequestModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/LeftArrow.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/manager/LoginManagerScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingNonMember.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingTitle.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInDefaultProfile.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInRequestScreen.kt
  presentation/src/main/res/drawable/ic_right_arrow.xml
  presentation/src/main/res/values/strings.xml
Labels: help wanted, design

#39 Add 커리큘럽 탭 화면 UI
  presentation/src/main/java/com/kusitms/presentation/model/notice/CurriculumUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/notice/NoticeUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/CurriculumList.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
Labels: feature
