Repository Mnseo/Kusitms_android, pull requests merged in 2024-02, with the labels that each got.

#98 [FEAT] 공지 대댓글 추가 및 삭제 시 갱신되지 않는 문제 수정
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
Labels: ✨ feature, 석준

#99 [FEAT] 출석 기능 UI 구현
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/home/AttendCurrentPayLoad.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/home/AttendInfoPayload.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/home/AttendPayload.kt
  data/src/main/java/com/kusitms/data/repository/HomeRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/home/AttendCurrentModel.kt
  domain/src/main/java/com/kusitms/domain/repository/HomeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/home/GetAttendCurrentListUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/home/GetAttendInfoUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/MemberSignOutUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle
  presentation/src/main/java/com/kusitms/presentation/model/home/attend/AttendUiState.kt
  presentation/src/main/java/com/kusitms/presentation/model/home/attend/AttendViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendButton.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendSnackbar.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/camera/CameraPreview.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/curriItem.kt
  presentation/src/main/java/com/kusitms/presentation/ui/splash/SplashScreen.kt
  presentation/src/main/res/drawable/ic_attend_check.xml
  presentation/src/main/res/drawable/ic_attend_late.xml
  presentation/src/main/res/drawable/ic_attend_non_check.xml
  presentation/src/main/res/drawable/ic_thumb.xml
  presentation/src/main/res/drawable/ic_up_arrow_fill.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 🎨 design, 민서

#100 [FEAT] 프로필 VIEW 피그마 변경 사항 반영
  presentation/src/main/java/com/kusitms/presentation/model/profile/PartList.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/ProfileViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileItem.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 아린

#102 Feature/attend UI
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/di/AuthTokenInterceptor.kt
  data/src/main/java/com/kusitms/data/remote/entity/request/LoginRequestBody.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/home/AttendInfoPayload.kt
  data/src/main/java/com/kusitms/data/repository/ChangePwRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/FindPwRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/HomeRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/SignInRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/home/AttendCurrentModel.kt
  domain/src/main/java/com/kusitms/domain/model/login/LoginMemberProfile.kt
  domain/src/main/java/com/kusitms/domain/repository/HomeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/home/GetAttendScoreUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/common/util/NavUtil.kt
  presentation/src/main/java/com/kusitms/presentation/model/home/attend/AttendViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/TopLevelDestination.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendButton.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/camera/CameraPreview.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/curriItem.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/LoginScreen.kt
Labels: 📍 refactor, 민서

#103 [FEAT] 프로필 설정 UI 구현
  presentation/src/main/java/com/kusitms/presentation/model/profile/edit/ProfileEditCategory.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/edit/ProfileEditUiState.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/edit/ProfileEditViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/edit/ProfileFilterList.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/profile/MyProfileScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/edit/ProfileAdd.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/edit/ProfileBasic.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/edit/ProfileEditScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/edit/ProfileLink.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/LinkBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/PartBottomSheet.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 아린

#106 [FIX] AuthInterceptor 수정 및 qrScan 구현
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/launch_transparent.xml
  app/src/main/res/values/themes.xml
  data/src/main/AndroidManifest.xml
  data/src/main/java/com/kusitms/data/local/AuthDataStore.kt
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/api/KusitmsTokenApi.kt
  data/src/main/java/com/kusitms/data/remote/di/AuthAuthenticator.kt
  data/src/main/java/com/kusitms/data/remote/di/AuthTokenInterceptor.kt
  data/src/main/java/com/kusitms/data/remote/di/NetworkModule.kt
  data/src/main/java/com/kusitms/data/remote/di/TokenManager.kt
  data/src/main/java/com/kusitms/data/remote/entity/request/AttendCheckRequestBody.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/home/AttendQrTextPayload.kt
  data/src/main/java/com/kusitms/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/HomeRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/LoginRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/SignInRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/home/AttendCheckModel.kt
  domain/src/main/java/com/kusitms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/kusitms/domain/repository/HomeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/home/GetAttendQrUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/home/GetNetworkStatusUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/home/PostAttendCheckUseCase.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/GetIsLoginUseCase.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsSnackBar.kt
  presentation/src/main/java/com/kusitms/presentation/model/home/attend/AttendViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SplashViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/CameraLayer.kt
  presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/LeftArrow.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/camera/CameraPreview.kt
  presentation/src/main/java/com/kusitms/presentation/ui/splash/SplashScreen.kt
  presentation/src/main/res/drawable/ic_camera_layer.xml
Labels: 📍 refactor, 민서

#110 [FIX] 로그아웃 오류 해결
  data/src/main/java/com/kusitms/data/remote/di/AuthTokenInterceptor.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/home/AttendInfoPayload.kt
  data/src/main/java/com/kusitms/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/home/AttendCurrentModel.kt
  domain/src/main/java/com/kusitms/domain/usecase/home/PostAttendCheckUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/model/home/attend/AttendViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/setting/SettingUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendButton.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/AttendScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/attend/camera/CameraPreview.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingMember.kt
  presentation/src/main/res/drawable/ic_union.xml
  presentation/src/main/res/values/strings.xml
Labels: 🔥 bug, 📍 refactor, 민서
