Repository Mnseo/Kusitms_android, pull requests merged in 2024-01, with the labels that each got.

#72 FIX: API Error
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/di/AuthTokenInterceptor.kt
  data/src/main/java/com/kusitms/data/remote/di/NetworkModule.kt
  data/src/main/java/com/kusitms/data/remote/util/NullOnEmptyConverterFactory.kt
  data/src/main/java/com/kusitms/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/kusitms/data/repository/SignInRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/login/TokenModel.kt
  domain/src/main/java/com/kusitms/domain/repository/AuthRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/signin/GetAuthTokenUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/common/theme/Color.kt
  presentation/src/main/java/com/kusitms/presentation/common/theme/Type.kt
  presentation/src/main/java/com/kusitms/presentation/model/login/LoginViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/setting/SettingUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SignInViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/signIn/SplashViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingMember.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/component/KusitmsLinkCheck.kt
  presentation/src/main/java/com/kusitms/presentation/ui/splash/SplashScreen.kt
Labels: 🔥 bug, ✨ feature, 민서

#75 [FIX]: 로그아웃 <-> 회원탈퇴 수정
  domain/src/main/java/com/kusitms/domain/usecase/signin/MemberLogOutUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/model/setting/SettingUiModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwSetNewPw.kt
  presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingMember.kt
  presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInProfileComplete.kt
  presentation/src/main/res/values/strings.xml
Labels: 🔥 bug, 민서

#81 [FEAT] 공지 대댓글 UI 및 대댓글 목록 조회
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/di/RepositoryModule.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/notice/NoticePayload.kt
  data/src/main/java/com/kusitms/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/notice/NoticeModel.kt
  domain/src/main/java/com/kusitms/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/GetChildCommentListUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
Labels: ✨ feature, 석준

#84 [FEAT] 프로필 API 연결 및 검색, 필터링 추가
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/profile/ProfilePayload.kt
  data/src/main/java/com/kusitms/data/repository/ProfileRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/model/profile/InterestModel.kt
  domain/src/main/java/com/kusitms/domain/model/profile/LinkModel.kt
  domain/src/main/java/com/kusitms/domain/model/profile/ProfileModel.kt
  domain/src/main/java/com/kusitms/domain/repository/ProfileRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/profile/GetProfileDetailUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/PartList.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/Profile.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/ProfileUiState.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/ProfileViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/search/ProfileSearchViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/profile/search/ProfileViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/login/LoginScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileItem.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailImage.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailInfo.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/detail/ProfileDetailViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/search/ProfileSearchExist.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/search/ProfileSearchField.kt
  presentation/src/main/java/com/kusitms/presentation/ui/profile/search/ProfileSearchScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 아린

#86 [FEAT] 대댓글 추가 연동 및 BottomSheet 수정
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/repository/NoticeRepositoryImpl.kt
  domain/src/main/java/com/kusitms/domain/repository/NoticeRepository.kt
  domain/src/main/java/com/kusitms/domain/usecase/notice/AddNoticeChildCommentUseCase.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailBottomSheet.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
Labels: ✨ feature, 석준

#87 [FEAT] 홈 화면 UI 구현
  .idea/deploymentTargetDropDown.xml
  domain/src/main/java/com/kusitms/domain/model/home/NoticeRecentModel.kt
  domain/src/main/java/com/kusitms/domain/model/home/TeamMatchingModel.kt
  presentation/src/main/java/com/kusitms/presentation/model/home/HomeUiState.kt
  presentation/src/main/java/com/kusitms/presentation/model/home/HomeViewModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/HomeCurriculum.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/HomeNotice.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/HomeProfile.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/HomeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/home/HomeTeam.kt
  presentation/src/main/res/drawable/ic_bell.xml
  presentation/src/main/res/drawable/ic_calendar.xml
  presentation/src/main/res/drawable/ic_hello_emoji.xml
  presentation/src/main/res/drawable/ic_location.xml
  presentation/src/main/res/drawable/ic_notice.xml
  presentation/src/main/res/drawable/ic_wifi.xml
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 아린

#93 [FEAT] 공지 검색 화면
  data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
  data/src/main/java/com/kusitms/data/remote/entity/response/notice/NoticePayload.kt
  domain/src/main/java/com/kusitms/domain/model/notice/NoticeModel.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
  presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeListScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/notice/search/NoticeSearchScreen.kt
  presentation/src/main/java/com/kusitms/presentation/ui/viewer/ImageViewerScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: ✨ feature, 석준
